common: &common
  adapter: postgresql
  username: sample_app
  password: sample_app.
  host: localhost
  port: 5432  
    
development:
  <<: *common
  database: sample_app_development

test:
  <<: *common
  database: sample_app_test

production:
  <<: *common
  database: sample_app_production
